
wget https://en.wikibooks.org/wiki/Category:Cookbook
wget https://en.wikibooks.org/wiki/Category:Ingredients
wget https://en.wikibooks.org/wiki/Category:Recipes
wget https://en.wikibooks.org/wiki/Category:Recipes
wget https://en.wikibooks.org/wiki/Cookbook:Requested_Recipes
wget https://en.wikibooks.org/wiki/Cookbook:1-2-3-4_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Aam_panna
wget https://en.wikibooks.org/wiki/Cookbook:Acorn_Squash_with_Orange_Marmalade
wget https://en.wikibooks.org/wiki/Cookbook:Shrimp_Fritters_\(Accra\)
wget https://en.wikibooks.org/wiki/Cookbook:Adobo
wget https://en.wikibooks.org/wiki/Cookbook:Agedashi_tofu
wget https://en.wikibooks.org/wiki/Cookbook:Alfredo_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Aloo_gobi
wget https://en.wikibooks.org/wiki/Cookbook:Potato_Samosas_\(Aloo_Pies\)
wget https://en.wikibooks.org/wiki/Cookbook:Aloo_masala
wget https://en.wikibooks.org/wiki/Cookbook:Angels_On_Horseback
wget https://en.wikibooks.org/wiki/Cookbook:A_Nice_Cup_of_Tea
wget https://en.wikibooks.org/wiki/Cookbook:Ambrosia_Fruit_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Red_Bean_Paste_\(Anko\)
wget https://en.wikibooks.org/wiki/Cookbook:Anzac_Biscuits
wget https://en.wikibooks.org/wiki/Cookbook:Appam
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Bundt_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Crisp
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Pie_I
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Pie_II
wget https://en.wikibooks.org/wiki/Cookbook:Apple_raisin_oat_muffins
wget https://en.wikibooks.org/wiki/Cookbook:Apple_Tapioca
wget https://en.wikibooks.org/wiki/Cookbook:Arroz_con_pollo
wget https://en.wikibooks.org/wiki/Cookbook:Arroz_negro
wget https://en.wikibooks.org/wiki/Cookbook:Rice_-_Molded_\(Arroz_Tapado\)
wget https://en.wikibooks.org/wiki/Cookbook:Artichoke_Hearts_Attack
wget https://en.wikibooks.org/wiki/Cookbook:Asparagus_soup
wget https://en.wikibooks.org/wiki/Cookbook:Atkins-friendly_Tira_Misu
wget https://en.wikibooks.org/wiki/Cookbook:Azteca
wget https://en.wikibooks.org/wiki/Cookbook:Hard_Tack_of_India_\(Baati\)
wget https://en.wikibooks.org/wiki/Cookbook:Baba_ganoush
wget https://en.wikibooks.org/wiki/Cookbook:Salt_Cod_and_Potato_Casserole_\(Bacalhau_%C3%A0_Gomes_de_S%C3%A1\)
wget https://en.wikibooks.org/wiki/Cookbook:Bacon_Cheese_Omelet
wget https://en.wikibooks.org/wiki/Cookbook:Baingan_Bartha_\(Southern\)
wget https://en.wikibooks.org/wiki/Cookbook:Baked_Lamb_and_Yogurt
wget https://en.wikibooks.org/wiki/Cookbook:Baked_Oatmeal
wget https://en.wikibooks.org/wiki/Cookbook:Baked_Pork_Chops
wget https://en.wikibooks.org/wiki/Cookbook:Banana_bread
wget https://en.wikibooks.org/wiki/Cookbook:Banana_nut_muffin
wget https://en.wikibooks.org/wiki/Cookbook:Banana_Chocolate_Bread_Pudding
wget https://en.wikibooks.org/wiki/Cookbook:Banana_Cream_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Banana_Cream_Pie_II
wget https://en.wikibooks.org/wiki/Cookbook:Pancake
wget https://en.wikibooks.org/wiki/Cookbook:B%C3%A1nh_M%C3%AC
wget https://en.wikibooks.org/wiki/Cookbook:Barbecued_Spare_Ribs
wget https://en.wikibooks.org/wiki/Cookbook:Barbecue_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Barbecue_Sauce_-_Kansas_City_style
wget https://en.wikibooks.org/wiki/Cookbook:Basic_Indian_Tomato_Gravy
wget https://en.wikibooks.org/wiki/Cookbook:Bean_Jahni_soup
wget https://en.wikibooks.org/wiki/Cookbook:B%C3%A9chamel_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Beef_and_Barley_Stew
wget https://en.wikibooks.org/wiki/Cookbook:Beef_Gravy_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Bengal_Potatoes
wget https://en.wikibooks.org/wiki/Cookbook:Biscuit
wget https://en.wikibooks.org/wiki/Cookbook:Biscuits
wget https://en.wikibooks.org/wiki/Cookbook:Biscuits_and_Gravy
wget https://en.wikibooks.org/wiki/Cookbook:Bison_Loaf
wget https://en.wikibooks.org/wiki/Cookbook:Black-Eyed_Peas_and_Kale
wget https://en.wikibooks.org/wiki/Cookbook:Bliny
wget https://en.wikibooks.org/wiki/Cookbook:Blondies
wget https://en.wikibooks.org/wiki/Cookbook:BLT_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Blueberry_muffin
wget https://en.wikibooks.org/wiki/Cookbook:Shrimp_and_Cassava_Sauce_of_Brazil_\(Bob%C3%B3_de_Camarao\)
wget https://en.wikibooks.org/wiki/Cookbook:Boerewors
wget https://en.wikibooks.org/wiki/Cookbook:Boiled_pasta
wget https://en.wikibooks.org/wiki/Cookbook:Boliche
wget https://en.wikibooks.org/wiki/Cookbook:B%C3%B6rek
wget https://en.wikibooks.org/wiki/Cookbook:Bouballe
wget https://en.wikibooks.org/wiki/Cookbook:Bouillabaisse
wget https://en.wikibooks.org/wiki/Cookbook:Bread
wget https://en.wikibooks.org/wiki/Cookbook:Breaded_Fried_Oysters
wget https://en.wikibooks.org/wiki/Cookbook:Breakfast_Waffles_\(Gluten-Free\)
wget https://en.wikibooks.org/wiki/Cookbook:Brigadeiro
wget https://en.wikibooks.org/wiki/Cookbook:British_Lemon_Meringue_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Broccoli_Stir_Fry
wget https://en.wikibooks.org/wiki/Cookbook:Brown_Gravy
wget https://en.wikibooks.org/wiki/Cookbook:Brown_Rice_with_Ground_Turkey
wget https://en.wikibooks.org/wiki/Cookbook:Brownie
wget https://en.wikibooks.org/wiki/Cookbook:Bruschetta
wget https://en.wikibooks.org/wiki/Cookbook:Bubble_and_Squeak
wget https://en.wikibooks.org/wiki/Cookbook:Bubble_Tea
wget https://en.wikibooks.org/wiki/Cookbook:Bulgur_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Bulgher_Burger
wget https://en.wikibooks.org/wiki/Cookbook:Bulgogi
wget https://en.wikibooks.org/wiki/Cookbook:Burrito
wget https://en.wikibooks.org/wiki/Cookbook:Butter_tart
wget https://en.wikibooks.org/wiki/Cookbook:Buuz
# wget /w/index.php?title=Cookbook:Cabbage_and_Bacon&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Caesar_Salad
wget https://en.wikibooks.org/wiki/Cookbook:California_Curry_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:California_Fusion_Peach_Salsa
wget https://en.wikibooks.org/wiki/Cookbook:Campfire_Trout
wget https://en.wikibooks.org/wiki/Cookbook:Candied_yams
wget https://en.wikibooks.org/wiki/Cookbook:Diana%27s_Candied_Sweet_Potatoes
wget https://en.wikibooks.org/wiki/Cookbook:Caramel
wget https://en.wikibooks.org/wiki/Cookbook:Cardamom_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Carpetbag_Steak
wget https://en.wikibooks.org/wiki/Cookbook:Cashew_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Cebiche_de_pescado
wget https://en.wikibooks.org/wiki/Cookbook:Century_egg
wget https://en.wikibooks.org/wiki/Cookbook:Ceviche_of_Shrimp_and_Sea_Bass
wget https://en.wikibooks.org/wiki/Cookbook:Chai_Tea
wget https://en.wikibooks.org/wiki/Cookbook:Chapati
wget https://en.wikibooks.org/wiki/Cookbook:Cheescake_cups
wget https://en.wikibooks.org/wiki/Cookbook:Chewy_Ginger_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Chicken_Broccoli
wget https://en.wikibooks.org/wiki/Cookbook:Chicken_Parmesan
wget https://en.wikibooks.org/wiki/Cookbook:Chicken_Pot_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Chicken_Pot_Pie_I
wget https://en.wikibooks.org/wiki/Cookbook:Chicken_Pot_Pie_II
# wget /w/index.php?title=Cookbook:Chicken_Soup&action=edit&redlink=1
# wget /w/index.php?title=Cookbook:Chicken_Stir-Fry&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Turkey_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Midwestern_Chicken_Wings
wget https://en.wikibooks.org/wiki/Cookbook:Chili
wget https://en.wikibooks.org/wiki/Cookbook:Chili_\(Vegan\)
wget https://en.wikibooks.org/wiki/Cookbook:Chili_con_carne
wget https://en.wikibooks.org/wiki/Cookbook:Chip
wget https://en.wikibooks.org/wiki/Cookbook:Potato_Chip
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Chip_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Chip_Cookies_\(Gluten-Free\)
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Fudge
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Mousse
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Pear_Bake
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_Sour-Cream_Icing
wget https://en.wikibooks.org/wiki/Cookbook:Chowder
wget https://en.wikibooks.org/wiki/Cookbook:Christmas_ham
wget https://en.wikibooks.org/wiki/Cookbook:Chuu_Chee_Fish
wget https://en.wikibooks.org/wiki/Cookbook:Nick%27s_Cinnamon_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Clam_Chowder
wget https://en.wikibooks.org/wiki/Cookbook:Clam_dip
wget https://en.wikibooks.org/wiki/Cookbook:Coconut_Chutney
wget https://en.wikibooks.org/wiki/Cookbook:Cola_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Boiled_Collard_Green
wget https://en.wikibooks.org/wiki/Cookbook:Coq_au_Vin
wget https://en.wikibooks.org/wiki/Cookbook:Corn_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Corn_Bread_2
wget https://en.wikibooks.org/wiki/Cookbook:Sweet_Cornbread
wget https://en.wikibooks.org/wiki/Cookbook:Cottage_Cheese_Eggs
wget https://en.wikibooks.org/wiki/Cookbook:Crab_Cakes
wget https://en.wikibooks.org/wiki/Cookbook:Crab_Quesadillas_with_Mango_Salsa
wget https://en.wikibooks.org/wiki/Cookbook:Cream_Cheese_Wontons
wget https://en.wikibooks.org/wiki/Cookbook:Creamed_Spinach
# wget /w/index.php?title=Cookbook:Creamy_BLT_Pasta&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Creme_Anglaise
wget https://en.wikibooks.org/wiki/Cookbook:Cr%C3%A8me_Br%C3%BBl%C3%A9e
wget https://en.wikibooks.org/wiki/Cookbook:Cr%C3%AApe
wget https://en.wikibooks.org/wiki/Cookbook:Crispy_Gingerbread_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Cucumber_and_Buttermilk_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Cucumber_Sprout_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Cupcakes
wget https://en.wikibooks.org/wiki/Cookbook:Curried_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Curry_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Curry_Fried_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Custard_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Date_Bar
wget https://en.wikibooks.org/wiki/Cookbook:Deep_Fried_Mars_Bar
wget https://en.wikibooks.org/wiki/Cookbook:Denver_Crunch
wget https://en.wikibooks.org/wiki/Cookbook:Dill_Cucumber_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Grilled_Vegetable_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Dosa
wget https://en.wikibooks.org/wiki/Cookbook:Duck_Confit
wget https://en.wikibooks.org/wiki/Cookbook:D%C3%B6ner_kebab
wget https://en.wikibooks.org/wiki/Cookbook:Easy_Maklubi
wget https://en.wikibooks.org/wiki/Cookbook:Easy_pasta_sauce
wget https://en.wikibooks.org/wiki/Cookbook:Easy_Scrambled_Eggs
wget https://en.wikibooks.org/wiki/Cookbook:Eel_alla_Milanese
wget https://en.wikibooks.org/wiki/Cookbook:Egg_Casserole
wget https://en.wikibooks.org/wiki/Cookbook:Egg_Butter
wget https://en.wikibooks.org/wiki/Cookbook:Egg_noodles
wget https://en.wikibooks.org/wiki/Cookbook:Egg_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Egg_Roll
wget https://en.wikibooks.org/wiki/Cookbook:Eggs_Connaught
wget https://en.wikibooks.org/wiki/Cookbook:Eggplant_and_Chickpea_Skillet
wget https://en.wikibooks.org/wiki/Cookbook:Eggplant_Pasta
wget https://en.wikibooks.org/wiki/Cookbook:Empanada
wget https://en.wikibooks.org/wiki/Cookbook:Eggnog
wget https://en.wikibooks.org/wiki/Cookbook:English_Field_Bean_Pate
wget https://en.wikibooks.org/wiki/Cookbook:Fairy_Cakes
wget https://en.wikibooks.org/wiki/Cookbook:Fast_cooking_recipes
wget https://en.wikibooks.org/wiki/Cookbook:Favorite_Beans_and_Rice
# wget /w/index.php?title=Cookbook:Fesenj%C4%81n&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Fiddlehead-Portobello_Linguine
wget https://en.wikibooks.org/wiki/Cookbook:Field_of_Dreams_Guacamole
wget https://en.wikibooks.org/wiki/Cookbook:Figgie_%27obbin
wget https://en.wikibooks.org/wiki/Cookbook:Clam_Chowder
wget https://en.wikibooks.org/wiki/Cookbook:Spanish_Flan
wget https://en.wikibooks.org/wiki/Cookbook:Focaccia_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Fool%27s_Gold_Loaf
wget https://en.wikibooks.org/wiki/Cookbook:Frapp%C3%A9_Coffee
wget https://en.wikibooks.org/wiki/Cookbook:French_Dip_Sandwiches
wget https://en.wikibooks.org/wiki/Cookbook:French_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:French_Fries
wget https://en.wikibooks.org/wiki/Cookbook:French_Toast
wget https://en.wikibooks.org/wiki/Cookbook:Fresh_Broadbeans_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Fresh_Mozzarella_Bruschetta
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Cheese_Balls_with_Sausage
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Eggs
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Fish
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Meatballs
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Okra
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Frikadeller
wget https://en.wikibooks.org/wiki/Cookbook:Frog%27s_Legs_%C3%A0_la_Parisienne
wget https://en.wikibooks.org/wiki/Cookbook:Fruit_Whip
wget https://en.wikibooks.org/wiki/Cookbook:Fry_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Gado-gado
wget https://en.wikibooks.org/wiki/Cookbook:Galaktoboureko
wget https://en.wikibooks.org/wiki/Cookbook:Garlic_bread
wget https://en.wikibooks.org/wiki/Cookbook:Garlic_croutons
wget https://en.wikibooks.org/wiki/Cookbook:Garlic_Lemon_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Garlic_Parmesan_Pasta
wget https://en.wikibooks.org/wiki/Cookbook:Garlic,_Tomato_and_Cheddar_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Gazpacho
wget https://en.wikibooks.org/wiki/Cookbook:Giblet_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Gingerbread
wget https://en.wikibooks.org/wiki/Cookbook:Ginny%27s_Toll_House_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Glazed_Sweet_Potatoes
wget https://en.wikibooks.org/wiki/Cookbook:Goulash
wget https://en.wikibooks.org/wiki/Cookbook:Goulash_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Grand_Union_Bacon
wget https://en.wikibooks.org/wiki/Cookbook:Hominy_Grits
wget https://en.wikibooks.org/wiki/Cookbook:Grilled_Cheese_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Grilled_Peanut_Butter_Sandwiches
wget https://en.wikibooks.org/wiki/Cookbook:Grilled_Portobello_Mushrooms
wget https://en.wikibooks.org/wiki/Cookbook:Grotten_Hans
wget https://en.wikibooks.org/wiki/Cookbook:Guacamole
wget https://en.wikibooks.org/wiki/Cookbook:Guacamole_Dip
wget https://en.wikibooks.org/wiki/Cookbook:Gyoza
wget https://en.wikibooks.org/wiki/Cookbook:Hamburger_Stoup
wget https://en.wikibooks.org/wiki/Cookbook:Hard_Tack
wget https://en.wikibooks.org/wiki/Cookbook:Herb_Bubble_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Hermits
wget https://en.wikibooks.org/wiki/Cookbook:Herring_soup
wget https://en.wikibooks.org/wiki/Cookbook:H.J_Burger_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Holland_Tea_Cakes
wget https://en.wikibooks.org/wiki/Cookbook:Pizza_Vanegas
wget https://en.wikibooks.org/wiki/Cookbook:Hominy_recipe
wget https://en.wikibooks.org/wiki/Cookbook:Hominy_Grits
wget https://en.wikibooks.org/wiki/Cookbook:Honey_Mustard_Salmon
wget https://en.wikibooks.org/wiki/Cookbook:Honey_Taffy
wget https://en.wikibooks.org/wiki/Cookbook:Hot_and_Sour_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Hot_and_Spicy_Dip
wget https://en.wikibooks.org/wiki/Cookbook:Hot_milk_cake
wget https://en.wikibooks.org/wiki/Cookbook:Hot_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Huevos_divorciados
wget https://en.wikibooks.org/wiki/Cookbook:Huevos_Rancheros
wget https://en.wikibooks.org/wiki/Cookbook:Hummus
wget https://en.wikibooks.org/wiki/Cookbook:Italian_risotto
wget https://en.wikibooks.org/wiki/Cookbook:Jamaican_Jerk_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Jamaican_Jerk_Spice
wget https://en.wikibooks.org/wiki/Cookbook:Jalebi
wget https://en.wikibooks.org/wiki/Cookbook:Jambalaya
wget https://en.wikibooks.org/wiki/Cookbook:Rainbow_Jell-O
wget https://en.wikibooks.org/wiki/Cookbook:Jangjorim
wget https://en.wikibooks.org/wiki/Cookbook:Kal_kals
wget https://en.wikibooks.org/wiki/Cookbook:Kashmiri_Pulao
wget https://en.wikibooks.org/wiki/Cookbook:Keralan_vegetable_stew
wget https://en.wikibooks.org/wiki/Cookbook:Khanom_Tian
wget https://en.wikibooks.org/wiki/Cookbook:Khara_pongal
wget https://en.wikibooks.org/wiki/Cookbook:Kimchi
wget https://en.wikibooks.org/wiki/Cookbook:Kiwi_and_Asian_Pear_in_Lemon_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Koeksisters
wget https://en.wikibooks.org/wiki/Cookbook:Kovaim
wget https://en.wikibooks.org/wiki/Cookbook:Kroppkakor
wget https://en.wikibooks.org/wiki/Cookbook:Kung_Pao_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Lancashire_Hotpot
wget https://en.wikibooks.org/wiki/Cookbook:Lasagne_with_bean_sauce
wget https://en.wikibooks.org/wiki/Cookbook:Latkes
wget https://en.wikibooks.org/wiki/Cookbook:Le_Tourin
wget https://en.wikibooks.org/wiki/Cookbook:Lemonade
wget https://en.wikibooks.org/wiki/Cookbook:Lemon_Meringue_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Lentil_soup
wget https://en.wikibooks.org/wiki/Cookbook:Lettuce_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Limoncello
wget https://en.wikibooks.org/wiki/Cookbook:Lomo_saltado
wget https://en.wikibooks.org/wiki/Cookbook:Luciabullar
wget https://en.wikibooks.org/wiki/Cookbook:Louis_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:Loukoumas
wget https://en.wikibooks.org/wiki/Cookbook:Low_Country_Shrimp_and_Grits
wget https://en.wikibooks.org/wiki/Cookbook:Lynn%27s_Veggie_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Macaroni_%26_Nutritional_Yeast
wget https://en.wikibooks.org/wiki/Cookbook:Macaroni_and_Cheese
wget https://en.wikibooks.org/wiki/Cookbook:Macaroni_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Macho_Nachos
wget https://en.wikibooks.org/wiki/Cookbook:Madeira_Honey_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Manhattan_Clam_Chowder
wget https://en.wikibooks.org/wiki/Cookbook:Marinara_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Masala_Chai
wget https://en.wikibooks.org/wiki/Cookbook:Masaledaar_chole
wget https://en.wikibooks.org/wiki/Cookbook:Mead
wget https://en.wikibooks.org/wiki/Cookbook:Meatballs
wget https://en.wikibooks.org/wiki/Cookbook:Fried_Meatballs
wget https://en.wikibooks.org/wiki/Cookbook:Swedish_Meatballs
wget https://en.wikibooks.org/wiki/Cookbook:Meatloaf
wget https://en.wikibooks.org/wiki/Cookbook:Menudo
wget https://en.wikibooks.org/wiki/Cookbook:Meringata
wget https://en.wikibooks.org/wiki/Cookbook:Mjeddrah
wget https://en.wikibooks.org/wiki/Cookbook:Mejadra
wget https://en.wikibooks.org/wiki/Cookbook:Microwave_Chocolate_Pudding
wget https://en.wikibooks.org/wiki/Cookbook:Microwave_Quesdilla
wget https://en.wikibooks.org/wiki/Cookbook:Microwave_Risotto
wget https://en.wikibooks.org/wiki/Cookbook:Microwaved_Artichoke
wget https://en.wikibooks.org/wiki/Cookbook:Midwestern_Chicken_Wings
wget https://en.wikibooks.org/wiki/Cookbook:Milkshake
wget https://en.wikibooks.org/wiki/Cookbook:Milk_toast
wget https://en.wikibooks.org/wiki/Cookbook:Mille_Cr%C3%AApe
wget https://en.wikibooks.org/wiki/Cookbook:Mincemeat_Tart
wget https://en.wikibooks.org/wiki/Cookbook:Minestrone_alla_Capucina
wget https://en.wikibooks.org/wiki/Cookbook:Minestrone_of_Rice_and_Turnips
wget https://en.wikibooks.org/wiki/Cookbook:Veal_with_lima_beans
wget https://en.wikibooks.org/wiki/Cookbook:Miso_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Mocha_icing
wget https://en.wikibooks.org/wiki/Cookbook:Modak
wget https://en.wikibooks.org/wiki/Cookbook:Molasses_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Molasses_Taffy
wget https://en.wikibooks.org/wiki/Cookbook:Moqueca_de_Peixe
wget https://en.wikibooks.org/wiki/Cookbook:Moules_Mariniere
wget https://en.wikibooks.org/wiki/Cookbook:MPT
wget https://en.wikibooks.org/wiki/Cookbook:M%C3%BCsli
wget https://en.wikibooks.org/wiki/Cookbook:Mudde
wget https://en.wikibooks.org/wiki/Cookbook:Mung_Beans_and_Brown_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Mussels_with_Potatoes
wget https://en.wikibooks.org/wiki/Cookbook:Neapolitan_sauce
wget https://en.wikibooks.org/wiki/Cookbook:Neapolitan_soup
wget https://en.wikibooks.org/wiki/Cookbook:Nachos
wget https://en.wikibooks.org/wiki/Cookbook:New_Mexico_Pork_Tamales
wget https://en.wikibooks.org/wiki/Cookbook:No-Bake_Chocolate_Chip_Cookie_Pie
wget https://en.wikibooks.org/wiki/Cookbook:No-Bake_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Not_Quite_Eggs_Benedict
wget https://en.wikibooks.org/wiki/Cookbook:Nut_Roll
wget https://en.wikibooks.org/wiki/Cookbook:Oatcake
wget https://en.wikibooks.org/wiki/Cookbook:Oatmeal_Banana_Waffle
wget https://en.wikibooks.org/wiki/Cookbook:Oatmeal_Raisin_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Raisin_Oatmeal_Muffins
wget https://en.wikibooks.org/wiki/Cookbook:Olive_Oil_Bread
wget https://en.wikibooks.org/wiki/Cookbook:%C3%98llebr%C3%B8d
wget https://en.wikibooks.org/wiki/Cookbook:Omelet_Recipes
wget https://en.wikibooks.org/wiki/Cookbook:One-Hour_Thanksgiving_Dinner
wget https://en.wikibooks.org/wiki/Cookbook:Onion_Chutney
wget https://en.wikibooks.org/wiki/Cookbook:Onion_Dip
wget https://en.wikibooks.org/wiki/Cookbook:Onion_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Orange_Hot_Chocolate
wget https://en.wikibooks.org/wiki/Cookbook:Orange_Julius
wget https://en.wikibooks.org/wiki/Cookbook:Orange_Sherbet_Smoothie
wget https://en.wikibooks.org/wiki/Cookbook:%27Out_of_Salad_Dressing%27_Salad_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:Ossobuco_Alla_Milanese
wget https://en.wikibooks.org/wiki/Cookbook:How_to_cook_oysters
wget https://en.wikibooks.org/wiki/Cookbook:Pad_Thai
wget https://en.wikibooks.org/wiki/Cookbook:Valencian_paella
wget https://en.wikibooks.org/wiki/Cookbook:Pancake
wget https://en.wikibooks.org/wiki/Cookbook:Pancakes_\(Vegan\)
wget https://en.wikibooks.org/wiki/Cookbook:Panch_Puran
wget https://en.wikibooks.org/wiki/Cookbook:Brown_Rice_with_Other_Starches_and_Vegetables_\(Pandora%27s_Feast\)
wget https://en.wikibooks.org/wiki/Cookbook:Papas_a_la_Huanca%C3%ADna
wget https://en.wikibooks.org/wiki/Cookbook:Paprika_Chicken
wget https://en.wikibooks.org/wiki/Cookbook:Pasta_Marinata
wget https://en.wikibooks.org/wiki/Cookbook:Pasta_Romanov
wget https://en.wikibooks.org/wiki/Cookbook:How_to_cook_pasta
wget https://en.wikibooks.org/wiki/Cookbook:Pate_Chinois
wget https://en.wikibooks.org/wiki/Cookbook:Pavlova
wget https://en.wikibooks.org/wiki/Cookbook:Peach_Cobbler
wget https://en.wikibooks.org/wiki/Cookbook:Peanut_Brittle
wget https://en.wikibooks.org/wiki/Cookbook:Peanut_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Pear_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Anise_Bread_\(Penia\)
# wget /w/index.php?title=Cookbook:Penne_Pasta_With_Sausage&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Pesto
wget https://en.wikibooks.org/wiki/Cookbook:Pickert
wget https://en.wikibooks.org/wiki/Cookbook:Pico_de_Gallo
wget https://en.wikibooks.org/wiki/Cookbook:Pierogi
wget https://en.wikibooks.org/wiki/Cookbook:Pineapple_Tarts
wget https://en.wikibooks.org/wiki/Cookbook:Pineapple_Teriyaki
wget https://en.wikibooks.org/wiki/Cookbook:Pineapple_upside-down_cake
wget https://en.wikibooks.org/wiki/Cookbook:Original_Pineapple_Upside-Down_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Pineapple_Upside-Down_Cake_in_a_Skillet
wget https://en.wikibooks.org/wiki/Cookbook:Quick_and_Delicious_Pineapple_Upside-Down_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Pi%C3%B1on_\(Spanish_Stovetop_Pot_Pie\)
wget https://en.wikibooks.org/wiki/Cookbook:Pizza
wget https://en.wikibooks.org/wiki/Cookbook:Pizza_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Pezzetti_di_Cavallo
wget https://en.wikibooks.org/wiki/Cookbook:Plank-Grilled_Salmon
wget https://en.wikibooks.org/wiki/Cookbook:Po%27_Boy
wget https://en.wikibooks.org/wiki/Cookbook:Polenta
wget https://en.wikibooks.org/wiki/Cookbook:Pork_Pot_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Potage_Parmentier
wget https://en.wikibooks.org/wiki/Cookbook:Potato-Chickpea_Curry
wget https://en.wikibooks.org/wiki/Cookbook:Potato_recipes
wget https://en.wikibooks.org/wiki/Cookbook:Potato_Skins
wget https://en.wikibooks.org/wiki/Cookbook:Potatoes_on_the_Half-Shell
wget https://en.wikibooks.org/wiki/Cookbook:Pound_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Poutine
wget https://en.wikibooks.org/wiki/Cookbook:Prekmurska_gibanica
wget https://en.wikibooks.org/wiki/Cookbook:Preserved_Lemon
wget https://en.wikibooks.org/wiki/Cookbook:Pretzel
wget https://en.wikibooks.org/wiki/Cookbook:Puliyodarai_Quick
wget https://en.wikibooks.org/wiki/Cookbook:Pulse_Chutney
wget https://en.wikibooks.org/wiki/Cookbook:Pumpkin_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Pumpkin_Scones
wget https://en.wikibooks.org/wiki/Cookbook:Pupusa
wget https://en.wikibooks.org/wiki/Cookbook:Pur%C3%A9e_Mongole
wget https://en.wikibooks.org/wiki/Cookbook:Quesadilla
wget https://en.wikibooks.org/wiki/Cookbook:Queso
wget https://en.wikibooks.org/wiki/Cookbook:Quiche
wget https://en.wikibooks.org/wiki/Cookbook:Quick_Marshmallow_Rice_Squares
wget https://en.wikibooks.org/wiki/Cookbook:Potato_Casserole_\(Rakott_Krumpli\)
wget https://en.wikibooks.org/wiki/Cookbook:Rainbow_Jell-O
wget https://en.wikibooks.org/wiki/Cookbook:Raisin_Oatmeal_Muffins
wget https://en.wikibooks.org/wiki/Cookbook:Raita
wget https://en.wikibooks.org/wiki/Cookbook:Ranch_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:Ratatouille
wget https://en.wikibooks.org/wiki/Cookbook:Red_Chile_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Red_Cross_Fudge
wget https://en.wikibooks.org/wiki/Cookbook:Red_Devils
wget https://en.wikibooks.org/wiki/Cookbook:Refried_Beans
wget https://en.wikibooks.org/wiki/Cookbook:Reuben_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Rhubarb_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Rhubarb_Crumble
wget https://en.wikibooks.org/wiki/Cookbook:Rice_an%27_Peas
wget https://en.wikibooks.org/wiki/Cookbook:Rice_and_Beef_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Rice_Bubble_cake
wget https://en.wikibooks.org/wiki/Cookbook:Rice_in_Fish_Broth-Sayyadieh
wget https://en.wikibooks.org/wiki/Cookbook:Rice_Pilaf
wget https://en.wikibooks.org/wiki/Cookbook:Rice_Pudding
wget https://en.wikibooks.org/wiki/Cookbook:Ricotta_Lasagne
wget https://en.wikibooks.org/wiki/Cookbook:Rigatoni_pasta_with_Ricotta_in_Tomato_Cream_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Risotto
wget https://en.wikibooks.org/wiki/Cookbook:Rissoles
wget https://en.wikibooks.org/wiki/Cookbook:Roast_Chicken_on_Salt
wget https://en.wikibooks.org/wiki/Cookbook:Roasted_Brined_Turkey
wget https://en.wikibooks.org/wiki/Cookbook:Roasted_Oysters_with_Madeira
wget https://en.wikibooks.org/wiki/Cookbook:Roasted_Vegetable_Pasta
wget https://en.wikibooks.org/wiki/Cookbook:Rolls
wget https://en.wikibooks.org/wiki/Cookbook:Rosemary_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Rosemary_Garlic_Baked_Potatoes
wget https://en.wikibooks.org/wiki/Cookbook:Ros%C3%B3%C5%82
wget https://en.wikibooks.org/wiki/Cookbook:Roti
wget https://en.wikibooks.org/wiki/Cookbook:Chapati
wget https://en.wikibooks.org/wiki/Cookbook:Roux
wget https://en.wikibooks.org/wiki/Cookbook:Cuisine_of_France
wget https://en.wikibooks.org/wiki/Cookbook:Rhubarb_Fool
wget https://en.wikibooks.org/wiki/Cookbook:Borscht
wget https://en.wikibooks.org/wiki/Cookbook:S%27more
wget https://en.wikibooks.org/wiki/Cookbook:Saffron_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Salsa
wget https://en.wikibooks.org/wiki/Cookbook:Samosa
wget https://en.wikibooks.org/wiki/Cookbook:San_Francisco_style_Scallop_Ceviche
wget https://en.wikibooks.org/wiki/Cookbook:Saucepan_Fudge_Crackle_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Scrambled_Eggs
wget https://en.wikibooks.org/wiki/Cookbook:German_Style_Sweet_Mustard_\(Senf\)
wget https://en.wikibooks.org/wiki/Cookbook:Seafood_Kebabs_with_Zhoug_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Sesame_Shrimp_Toast
wget https://en.wikibooks.org/wiki/Cookbook:Shakshuka
wget https://en.wikibooks.org/wiki/Cookbook:Sheer_khurma
wget https://en.wikibooks.org/wiki/Cookbook:Shepherd%27s_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Silvash_Gombotz
wget https://en.wikibooks.org/wiki/Cookbook:Simple_Nachos
wget https://en.wikibooks.org/wiki/Cookbook:Simple_Roasted_Oysters
wget https://en.wikibooks.org/wiki/Cookbook:Sirniki
wget https://en.wikibooks.org/wiki/Cookbook:Six_Layer_Casserole
wget https://en.wikibooks.org/wiki/Cookbook:S%27more
wget https://en.wikibooks.org/wiki/Cookbook:Sockerdricka
wget https://en.wikibooks.org/wiki/Cookbook:Soda_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Pretzel
wget https://en.wikibooks.org/wiki/Cookbook:Sour_Cream_Dip
wget https://en.wikibooks.org/wiki/Cookbook:Southwest_Pasta
wget https://en.wikibooks.org/wiki/Cookbook:Southwestern_Scramble
wget https://en.wikibooks.org/wiki/Cookbook:Soup_with_Suppl%C3%AC
wget https://en.wikibooks.org/wiki/Cookbook:Soy_Protein_Bread
wget https://en.wikibooks.org/wiki/Cookbook:Space_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Spaghetti_alla_Carbonara
wget https://en.wikibooks.org/wiki/Cookbook:Spanish_Omelet
wget https://en.wikibooks.org/wiki/Cookbook:Spiced_Pumpkin_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Spicy_Chicken_Casserole
wget https://en.wikibooks.org/wiki/Cookbook:Spicy_feta_burger
wget https://en.wikibooks.org/wiki/Cookbook:Sprout_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Sponge_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Stargazy_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Steak_tartare
wget https://en.wikibooks.org/wiki/Cookbook:Steamed_Artichoke
wget https://en.wikibooks.org/wiki/Cookbook:Steamed_Buns_with_BBQ_Pork
wget https://en.wikibooks.org/wiki/Cookbook:Steamed_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Stewed_dry_figs_dessert
wget https://en.wikibooks.org/wiki/Cookbook:Stewed_Oysters
wget https://en.wikibooks.org/wiki/Cookbook:Strudel
wget https://en.wikibooks.org/wiki/Cookbook:Broccoli_Stir_Fry
wget https://en.wikibooks.org/wiki/Cookbook:Stuffed_Mushrooms_with_Crabmeat
wget https://en.wikibooks.org/wiki/Cookbook:Stuffed_Portabella_Mushrooms
wget https://en.wikibooks.org/wiki/Cookbook:Succotash
wget https://en.wikibooks.org/wiki/Cookbook:Grannie_Gilbert%27s_Sugar_Cookies
wget https://en.wikibooks.org/wiki/Cookbook:Sunglow_Motel-Cafe_Pickle_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Sunshine_Cake
wget https://en.wikibooks.org/wiki/Cookbook:Sushi
wget https://en.wikibooks.org/wiki/Cookbook:Sweet_and_Sour
wget https://en.wikibooks.org/wiki/Cookbook:Sweet_Cornbread
wget https://en.wikibooks.org/wiki/Cookbook:Sweet_pongal
wget https://en.wikibooks.org/wiki/Cookbook:Swedish_Meatballs
wget https://en.wikibooks.org/wiki/Cookbook:Swiss_pudding
wget https://en.wikibooks.org/wiki/Cookbook:Tabouli
wget https://en.wikibooks.org/wiki/Cookbook:Tabula
wget https://en.wikibooks.org/wiki/Cookbook:Tadka_dhal
wget https://en.wikibooks.org/wiki/Cookbook:Tahini_Goddess_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:Tandoori_masala
wget https://en.wikibooks.org/wiki/Cookbook:Tangerine_Jelly
wget https://en.wikibooks.org/wiki/Cookbook:Tarbes_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Tartiflette
wget https://en.wikibooks.org/wiki/Cookbook:Tater_Tot_Casserole
wget https://en.wikibooks.org/wiki/Cookbook:Tea_Eggs
wget https://en.wikibooks.org/wiki/Cookbook:Tempura
wget https://en.wikibooks.org/wiki/Cookbook:Teriyaki
wget https://en.wikibooks.org/wiki/Cookbook:Texas_Easy_Chili
# wget /w/index.php?title=Cookbook:The_Concoction&action=edit&redlink=1
wget https://en.wikibooks.org/wiki/Cookbook:Thousand_Island_Dressing
wget https://en.wikibooks.org/wiki/Cookbook:Three_Ginger_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Tiramisu
wget https://en.wikibooks.org/wiki/Cookbook:Toasted_Cheese_Sandwich
wget https://en.wikibooks.org/wiki/Cookbook:Toasted_Ravioli
wget https://en.wikibooks.org/wiki/Cookbook:Tofu
wget https://en.wikibooks.org/wiki/Cookbook:Tofu_Pancake
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_Curry
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_Coulis
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_Pasta
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_Sauce_Piquante
wget https://en.wikibooks.org/wiki/Cookbook:Tomatoes_with_Cheese_Stuffing
wget https://en.wikibooks.org/wiki/Cookbook:Tuna_Curry
wget https://en.wikibooks.org/wiki/Cookbook:Tuna_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Turkey_Biscuit
wget https://en.wikibooks.org/wiki/Cookbook:Turkey_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Turkey_Wrap
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_and_Onion_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Tomato_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Traditional_Pilau_Rice
wget https://en.wikibooks.org/wiki/Cookbook:Tri-colored_Autumn_Rice_Balls
wget https://en.wikibooks.org/wiki/Cookbook:Turkey_and_Bacon_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Ukrainian_Cornmeal_Stuffing_\(Nachynka\)
wget https://en.wikibooks.org/wiki/Cookbook:Ukrainian_Cabbage_Soup_\(Kapusniak\)
wget https://en.wikibooks.org/wiki/Cookbook:Umeboshi
wget https://en.wikibooks.org/wiki/Cookbook:Ume-shu
wget https://en.wikibooks.org/wiki/Cookbook:Upeseru
wget https://en.wikibooks.org/wiki/Cookbook:Chocolate_chip_cookies
wget https://en.wikibooks.org/wiki/Cookbook:Chili_\(Vegan\)
wget https://en.wikibooks.org/wiki/Cookbook:Vegetable_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Ale,_Mustard_and_Winter_Vegetable_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Aubergine_and_Onion_Vegetable_Pie
wget https://en.wikibooks.org/wiki/Cookbook:Vegetable_Stew_and_Dumplings
wget https://en.wikibooks.org/wiki/Cookbook:Vegetarian_Gravy
wget https://en.wikibooks.org/wiki/Cookbook:Vegetarian_Soft_Tacos
wget https://en.wikibooks.org/wiki/Cookbook:Waldorf_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Wheat_grass_juice
wget https://en.wikibooks.org/wiki/Cookbook:Whipped_Cream
wget https://en.wikibooks.org/wiki/Cookbook:White_Bread
wget https://en.wikibooks.org/wiki/Cookbook:White_Sauce
wget https://en.wikibooks.org/wiki/Cookbook:Wiejska
wget https://en.wikibooks.org/wiki/Cookbook:Wild_Spinach_and_Lemon_Salad
wget https://en.wikibooks.org/wiki/Cookbook:Windsor_pudding
wget https://en.wikibooks.org/wiki/Cookbook:Wonton_Soup
wget https://en.wikibooks.org/wiki/Cookbook:Wonton_Wrapper
wget https://en.wikibooks.org/wiki/Cookbook:Yam_casserole
wget https://en.wikibooks.org/wiki/Cookbook:Yorkshire_Pudding
wget https://en.wikibooks.org/wiki/Cookbook:Yorkshire_Pudding_\(Vegan\)
wget https://en.wikibooks.org/wiki/Cookbook:Yogurt_Dip
wget https://en.wikibooks.org/wiki/Cookbook:Yurvarlak
wget https://en.wikibooks.org/wiki/Cookbook:Zupa_Og%C3%B3rkowa
wget https://en.wikibooks.org/wiki/Cookbook:Zuppa_Toscana
