xsltproc -html stripWikiRecipe.xsl temp/Cookbook:\'Out_of_Salad_Dressing\'_Salad_Dressing" > "data/Cookbook:\'Out_of_Salad_Dressing\'_Salad_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:1-2-3-4_Cake > data/Cookbook:1-2-3-4_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:A_Nice_Cup_of_Tea > data/Cookbook:A_Nice_Cup_of_Tea
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Aam_panna > data/Cookbook:Aam_panna
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Acorn_Squash_with_Orange_Marmalade > data/Cookbook:Acorn_Squash_with_Orange_Marmalade
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Adobo > data/Cookbook:Adobo
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Agedashi_tofu > data/Cookbook:Agedashi_tofu
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ale,_Mustard_and_Winter_Vegetable_Pie > data/Cookbook:Ale,_Mustard_and_Winter_Vegetable_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Alfredo_Sauce > data/Cookbook:Alfredo_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Aloo_gobi > data/Cookbook:Aloo_gobi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Aloo_masala > data/Cookbook:Aloo_masala
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ambrosia_Fruit_Salad > data/Cookbook:Ambrosia_Fruit_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Angels_On_Horseback > data/Cookbook:Angels_On_Horseback
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Anise_Bread_\(Penia\) > data/Cookbook:Anise_Bread_\(Penia\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Anzac_Biscuits > data/Cookbook:Anzac_Biscuits
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Appam > data/Cookbook:Appam
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Bundt_Cake > data/Cookbook:Apple_Bundt_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Crisp > data/Cookbook:Apple_Crisp
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Pie > data/Cookbook:Apple_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Pie_I > data/Cookbook:Apple_Pie_I
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Pie_II > data/Cookbook:Apple_Pie_II
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_Tapioca > data/Cookbook:Apple_Tapioca
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Apple_raisin_oat_muffins > data/Cookbook:Apple_raisin_oat_muffins
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Arroz_con_pollo > data/Cookbook:Arroz_con_pollo
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Arroz_negro > data/Cookbook:Arroz_negro
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Artichoke_Hearts_Attack > data/Cookbook:Artichoke_Hearts_Attack
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Asparagus_soup > data/Cookbook:Asparagus_soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Atkins-friendly_Tira_Misu > data/Cookbook:Atkins-friendly_Tira_Misu
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Aubergine_and_Onion_Vegetable_Pie > data/Cookbook:Aubergine_and_Onion_Vegetable_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Azteca > data/Cookbook:Azteca
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:BLT_Sandwich > data/Cookbook:BLT_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Baba_ganoush > data/Cookbook:Baba_ganoush
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bacon_Cheese_Omelet > data/Cookbook:Bacon_Cheese_Omelet
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Baingan_Bartha_\(Southern\) > data/Cookbook:Baingan_Bartha_\(Southern\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Baked_Lamb_and_Yogurt > data/Cookbook:Baked_Lamb_and_Yogurt
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Baked_Oatmeal > data/Cookbook:Baked_Oatmeal
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Baked_Pork_Chops > data/Cookbook:Baked_Pork_Chops
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Banana_Chocolate_Bread_Pudding > data/Cookbook:Banana_Chocolate_Bread_Pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Banana_Cream_Pie > data/Cookbook:Banana_Cream_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Banana_Cream_Pie_II > data/Cookbook:Banana_Cream_Pie_II
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Banana_bread > data/Cookbook:Banana_bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Banana_nut_muffin > data/Cookbook:Banana_nut_muffin
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Barbecue_Sauce > data/Cookbook:Barbecue_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Barbecue_Sauce_-_Kansas_City_style > data/Cookbook:Barbecue_Sauce_-_Kansas_City_style
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Barbecued_Spare_Ribs > data/Cookbook:Barbecued_Spare_Ribs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Basic_Indian_Tomato_Gravy > data/Cookbook:Basic_Indian_Tomato_Gravy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bean_Jahni_soup > data/Cookbook:Bean_Jahni_soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Beef_Gravy_Soup > data/Cookbook:Beef_Gravy_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Beef_and_Barley_Stew > data/Cookbook:Beef_and_Barley_Stew
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bengal_Potatoes > data/Cookbook:Bengal_Potatoes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Biscuit > data/Cookbook:Biscuit
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Biscuits > data/Cookbook:Biscuits
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Biscuits_and_Gravy > data/Cookbook:Biscuits_and_Gravy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bison_Loaf > data/Cookbook:Bison_Loaf
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Black-Eyed_Peas_and_Kale > data/Cookbook:Black-Eyed_Peas_and_Kale
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bliny > data/Cookbook:Bliny
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Blondies > data/Cookbook:Blondies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Blueberry_muffin > data/Cookbook:Blueberry_muffin
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Boerewors > data/Cookbook:Boerewors
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Boiled_Collard_Green > data/Cookbook:Boiled_Collard_Green
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Boiled_pasta > data/Cookbook:Boiled_pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Boliche > data/Cookbook:Boliche
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Borscht > data/Cookbook:Borscht
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bouballe > data/Cookbook:Bouballe
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bouillabaisse > data/Cookbook:Bouillabaisse
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bread > data/Cookbook:Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Breaded_Fried_Oysters > data/Cookbook:Breaded_Fried_Oysters
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Breakfast_Waffles_\(Gluten-Free\) > data/Cookbook:Breakfast_Waffles_\(Gluten-Free\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Brigadeiro > data/Cookbook:Brigadeiro
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:British_Lemon_Meringue_Pie > data/Cookbook:British_Lemon_Meringue_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Broccoli_Stir_Fry > data/Cookbook:Broccoli_Stir_Fry
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Brown_Gravy > data/Cookbook:Brown_Gravy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Brown_Rice_with_Ground_Turkey > data/Cookbook:Brown_Rice_with_Ground_Turkey
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Brown_Rice_with_Other_Starches_and_Vegetables_\(Pandora\'s_Feast\) > data/Cookbook:Brown_Rice_with_Other_Starches_and_Vegetables_\(Pandora\'s_Feast\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Brownie > data/Cookbook:Brownie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bruschetta > data/Cookbook:Bruschetta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bubble_Tea > data/Cookbook:Bubble_Tea
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bubble_and_Squeak > data/Cookbook:Bubble_and_Squeak
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bulgher_Burger > data/Cookbook:Bulgher_Burger
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bulgogi > data/Cookbook:Bulgogi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bulgur_Bread > data/Cookbook:Bulgur_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Burrito > data/Cookbook:Burrito
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Butter_tart > data/Cookbook:Butter_tart
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Buuz > data/Cookbook:Buuz
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Bánh_Mì > data/Cookbook:Bánh_Mì
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Béchamel_Sauce > data/Cookbook:Béchamel_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Börek > data/Cookbook:Börek
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Caesar_Salad > data/Cookbook:Caesar_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:California_Curry_Chicken > data/Cookbook:California_Curry_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:California_Fusion_Peach_Salsa > data/Cookbook:California_Fusion_Peach_Salsa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Campfire_Trout > data/Cookbook:Campfire_Trout
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Candied_yams > data/Cookbook:Candied_yams
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Caramel > data/Cookbook:Caramel
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cardamom_Bread > data/Cookbook:Cardamom_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Carpetbag_Steak > data/Cookbook:Carpetbag_Steak
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cashew_Chicken > data/Cookbook:Cashew_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cebiche_de_pescado > data/Cookbook:Cebiche_de_pescado
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Century_egg > data/Cookbook:Century_egg
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ceviche_of_Shrimp_and_Sea_Bass > data/Cookbook:Ceviche_of_Shrimp_and_Sea_Bass
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chai_Tea > data/Cookbook:Chai_Tea
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chapati > data/Cookbook:Chapati
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cheescake_cups > data/Cookbook:Cheescake_cups
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chewy_Ginger_Cookies > data/Cookbook:Chewy_Ginger_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chicken_Broccoli > data/Cookbook:Chicken_Broccoli
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chicken_Parmesan > data/Cookbook:Chicken_Parmesan
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chicken_Pot_Pie > data/Cookbook:Chicken_Pot_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chicken_Pot_Pie_I > data/Cookbook:Chicken_Pot_Pie_I
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chicken_Pot_Pie_II > data/Cookbook:Chicken_Pot_Pie_II
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chili > data/Cookbook:Chili
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chili_\(Vegan\) > data/Cookbook:Chili_\(Vegan\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chili_con_carne > data/Cookbook:Chili_con_carne
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chip > data/Cookbook:Chip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Cake > data/Cookbook:Chocolate_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Chip_Cookies > data/Cookbook:Chocolate_Chip_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Chip_Cookies_\(Gluten-Free\) > data/Cookbook:Chocolate_Chip_Cookies_\(Gluten-Free\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Fudge > data/Cookbook:Chocolate_Fudge
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Mousse > data/Cookbook:Chocolate_Mousse
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Pear_Bake > data/Cookbook:Chocolate_Pear_Bake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_Sour-Cream_Icing > data/Cookbook:Chocolate_Sour-Cream_Icing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chocolate_chip_cookies > data/Cookbook:Chocolate_chip_cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chowder > data/Cookbook:Chowder
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Christmas_ham > data/Cookbook:Christmas_ham
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Chuu_Chee_Fish > data/Cookbook:Chuu_Chee_Fish
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Clam_Chowder > data/Cookbook:Clam_Chowder
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Clam_dip > data/Cookbook:Clam_dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Coconut_Chutney > data/Cookbook:Coconut_Chutney
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cola_Cake > data/Cookbook:Cola_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Coq_au_Vin > data/Cookbook:Coq_au_Vin
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Corn_Bread > data/Cookbook:Corn_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Corn_Bread_2 > data/Cookbook:Corn_Bread_2
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cottage_Cheese_Eggs > data/Cookbook:Cottage_Cheese_Eggs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Crab_Cakes > data/Cookbook:Crab_Cakes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Crab_Quesadillas_with_Mango_Salsa > data/Cookbook:Crab_Quesadillas_with_Mango_Salsa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cream_Cheese_Wontons > data/Cookbook:Cream_Cheese_Wontons
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Creamed_Spinach > data/Cookbook:Creamed_Spinach
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Creme_Anglaise > data/Cookbook:Creme_Anglaise
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Crispy_Gingerbread_Cookies > data/Cookbook:Crispy_Gingerbread_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Crème_Brûlée > data/Cookbook:Crème_Brûlée
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Crêpe > data/Cookbook:Crêpe
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cucumber_Sprout_Sandwich > data/Cookbook:Cucumber_Sprout_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cucumber_and_Buttermilk_Soup > data/Cookbook:Cucumber_and_Buttermilk_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cuisine_of_France > data/Cookbook:Cuisine_of_France
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Cupcakes > data/Cookbook:Cupcakes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Curried_Rice > data/Cookbook:Curried_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Curry_Chicken > data/Cookbook:Curry_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Curry_Fried_Rice > data/Cookbook:Curry_Fried_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Custard_Pie > data/Cookbook:Custard_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Date_Bar > data/Cookbook:Date_Bar
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Deep_Fried_Mars_Bar > data/Cookbook:Deep_Fried_Mars_Bar
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Denver_Crunch > data/Cookbook:Denver_Crunch
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Diana\'s_Candied_Sweet_Potatoes > data/Cookbook:Diana\'s_Candied_Sweet_Potatoes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Dill_Cucumber_Salad > data/Cookbook:Dill_Cucumber_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Dosa > data/Cookbook:Dosa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Duck_Confit > data/Cookbook:Duck_Confit
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Döner_kebab > data/Cookbook:Döner_kebab
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Easy_Maklubi > data/Cookbook:Easy_Maklubi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Easy_Scrambled_Eggs > data/Cookbook:Easy_Scrambled_Eggs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Easy_pasta_sauce > data/Cookbook:Easy_pasta_sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Eel_alla_Milanese > data/Cookbook:Eel_alla_Milanese
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Egg_Butter > data/Cookbook:Egg_Butter
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Egg_Casserole > data/Cookbook:Egg_Casserole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Egg_Rice > data/Cookbook:Egg_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Egg_Roll > data/Cookbook:Egg_Roll
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Egg_noodles > data/Cookbook:Egg_noodles
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Eggnog > data/Cookbook:Eggnog
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Eggplant_Pasta > data/Cookbook:Eggplant_Pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Eggplant_and_Chickpea_Skillet > data/Cookbook:Eggplant_and_Chickpea_Skillet
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Eggs_Connaught > data/Cookbook:Eggs_Connaught
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Empanada > data/Cookbook:Empanada
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:English_Field_Bean_Pate > data/Cookbook:English_Field_Bean_Pate
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fairy_Cakes > data/Cookbook:Fairy_Cakes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fast_cooking_recipes > data/Cookbook:Fast_cooking_recipes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Favorite_Beans_and_Rice > data/Cookbook:Favorite_Beans_and_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fiddlehead-Portobello_Linguine > data/Cookbook:Fiddlehead-Portobello_Linguine
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Field_of_Dreams_Guacamole > data/Cookbook:Field_of_Dreams_Guacamole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Figgie_\'obbin > data/Cookbook:Figgie_\'obbin
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Focaccia_Bread > data/Cookbook:Focaccia_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fool\'s_Gold_Loaf > data/Cookbook:Fool\'s_Gold_Loaf
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Frappé_Coffee > data/Cookbook:Frappé_Coffee
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:French_Dip_Sandwiches > data/Cookbook:French_Dip_Sandwiches
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:French_Dressing > data/Cookbook:French_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:French_Fries > data/Cookbook:French_Fries
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:French_Toast > data/Cookbook:French_Toast
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fresh_Broadbeans_Salad > data/Cookbook:Fresh_Broadbeans_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fresh_Mozzarella_Bruschetta > data/Cookbook:Fresh_Mozzarella_Bruschetta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Cheese_Balls_with_Sausage > data/Cookbook:Fried_Cheese_Balls_with_Sausage
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Eggs > data/Cookbook:Fried_Eggs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Fish > data/Cookbook:Fried_Fish
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Meatballs > data/Cookbook:Fried_Meatballs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Okra > data/Cookbook:Fried_Okra
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fried_Rice > data/Cookbook:Fried_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Frikadeller > data/Cookbook:Frikadeller
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Frog\'s_Legs_à_la_Parisienne > data/Cookbook:Frog\'s_Legs_à_la_Parisienne
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fruit_Whip > data/Cookbook:Fruit_Whip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Fry_Bread > data/Cookbook:Fry_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Gado-gado > data/Cookbook:Gado-gado
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Galaktoboureko > data/Cookbook:Galaktoboureko
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Garlic,_Tomato_and_Cheddar_Sandwich > data/Cookbook:Garlic,_Tomato_and_Cheddar_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Garlic_Lemon_Chicken > data/Cookbook:Garlic_Lemon_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Garlic_Parmesan_Pasta > data/Cookbook:Garlic_Parmesan_Pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Garlic_bread > data/Cookbook:Garlic_bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Garlic_croutons > data/Cookbook:Garlic_croutons
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Gazpacho > data/Cookbook:Gazpacho
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:German_Style_Sweet_Mustard_\(Senf\) > data/Cookbook:German_Style_Sweet_Mustard_\(Senf\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Giblet_Soup > data/Cookbook:Giblet_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Gingerbread > data/Cookbook:Gingerbread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ginny\'s_Toll_House_Cookies > data/Cookbook:Ginny\'s_Toll_House_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Glazed_Sweet_Potatoes > data/Cookbook:Glazed_Sweet_Potatoes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Goulash > data/Cookbook:Goulash
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Goulash_Soup > data/Cookbook:Goulash_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grand_Union_Bacon > data/Cookbook:Grand_Union_Bacon
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grannie_Gilbert\'s_Sugar_Cookies > data/Cookbook:Grannie_Gilbert\'s_Sugar_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grilled_Cheese_Sandwich > data/Cookbook:Grilled_Cheese_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grilled_Peanut_Butter_Sandwiches > data/Cookbook:Grilled_Peanut_Butter_Sandwiches
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grilled_Portobello_Mushrooms > data/Cookbook:Grilled_Portobello_Mushrooms
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grilled_Vegetable_Sandwich > data/Cookbook:Grilled_Vegetable_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Grotten_Hans > data/Cookbook:Grotten_Hans
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Guacamole > data/Cookbook:Guacamole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Guacamole_Dip > data/Cookbook:Guacamole_Dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Gyoza > data/Cookbook:Gyoza
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:H.J_Burger_Sauce > data/Cookbook:H.J_Burger_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hamburger_Stoup > data/Cookbook:Hamburger_Stoup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hard_Tack > data/Cookbook:Hard_Tack
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hard_Tack_of_India_\(Baati\) > data/Cookbook:Hard_Tack_of_India_\(Baati\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Herb_Bubble_Bread > data/Cookbook:Herb_Bubble_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hermits > data/Cookbook:Hermits
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Herring_soup > data/Cookbook:Herring_soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Holland_Tea_Cakes > data/Cookbook:Holland_Tea_Cakes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hominy_Grits > data/Cookbook:Hominy_Grits
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hominy_recipe > data/Cookbook:Hominy_recipe
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Honey_Mustard_Salmon > data/Cookbook:Honey_Mustard_Salmon
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Honey_Taffy > data/Cookbook:Honey_Taffy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hot_Sauce > data/Cookbook:Hot_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hot_and_Sour_Soup > data/Cookbook:Hot_and_Sour_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hot_and_Spicy_Dip > data/Cookbook:Hot_and_Spicy_Dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hot_milk_cake > data/Cookbook:Hot_milk_cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:How_to_cook_oysters > data/Cookbook:How_to_cook_oysters
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:How_to_cook_pasta > data/Cookbook:How_to_cook_pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Huevos_Rancheros > data/Cookbook:Huevos_Rancheros
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Huevos_divorciados > data/Cookbook:Huevos_divorciados
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Hummus > data/Cookbook:Hummus
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Italian_risotto > data/Cookbook:Italian_risotto
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Jalebi > data/Cookbook:Jalebi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Jamaican_Jerk_Chicken > data/Cookbook:Jamaican_Jerk_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Jamaican_Jerk_Spice > data/Cookbook:Jamaican_Jerk_Spice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Jambalaya > data/Cookbook:Jambalaya
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Jangjorim > data/Cookbook:Jangjorim
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kal_kals > data/Cookbook:Kal_kals
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kashmiri_Pulao > data/Cookbook:Kashmiri_Pulao
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Keralan_vegetable_stew > data/Cookbook:Keralan_vegetable_stew
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Khanom_Tian > data/Cookbook:Khanom_Tian
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Khara_pongal > data/Cookbook:Khara_pongal
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kimchi > data/Cookbook:Kimchi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kiwi_and_Asian_Pear_in_Lemon_Sauce > data/Cookbook:Kiwi_and_Asian_Pear_in_Lemon_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Koeksisters > data/Cookbook:Koeksisters
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kovaim > data/Cookbook:Kovaim
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kroppkakor > data/Cookbook:Kroppkakor
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Kung_Pao_Chicken > data/Cookbook:Kung_Pao_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lancashire_Hotpot > data/Cookbook:Lancashire_Hotpot
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lasagne_with_bean_sauce > data/Cookbook:Lasagne_with_bean_sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Latkes > data/Cookbook:Latkes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Le_Tourin > data/Cookbook:Le_Tourin
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lemon_Meringue_Pie > data/Cookbook:Lemon_Meringue_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lemonade > data/Cookbook:Lemonade
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lentil_soup > data/Cookbook:Lentil_soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lettuce_Soup > data/Cookbook:Lettuce_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Limoncello > data/Cookbook:Limoncello
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lomo_saltado > data/Cookbook:Lomo_saltado
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Louis_Dressing > data/Cookbook:Louis_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Loukoumas > data/Cookbook:Loukoumas
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Low_Country_Shrimp_and_Grits > data/Cookbook:Low_Country_Shrimp_and_Grits
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Luciabullar > data/Cookbook:Luciabullar
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Lynn\'s_Veggie_Salad > data/Cookbook:Lynn\'s_Veggie_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:MPT > data/Cookbook:MPT
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Macaroni_&_Nutritional_Yeast > data/Cookbook:Macaroni_&_Nutritional_Yeast
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Macaroni_Salad > data/Cookbook:Macaroni_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Macaroni_and_Cheese > data/Cookbook:Macaroni_and_Cheese
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Macho_Nachos > data/Cookbook:Macho_Nachos
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Madeira_Honey_Cake > data/Cookbook:Madeira_Honey_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Manhattan_Clam_Chowder > data/Cookbook:Manhattan_Clam_Chowder
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Marinara_Sauce > data/Cookbook:Marinara_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Masala_Chai > data/Cookbook:Masala_Chai
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Masaledaar_chole > data/Cookbook:Masaledaar_chole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mead > data/Cookbook:Mead
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Meatballs > data/Cookbook:Meatballs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Meatloaf > data/Cookbook:Meatloaf
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mejadra > data/Cookbook:Mejadra
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Menudo > data/Cookbook:Menudo
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Meringata > data/Cookbook:Meringata
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Microwave_Chocolate_Pudding > data/Cookbook:Microwave_Chocolate_Pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Microwave_Quesdilla > data/Cookbook:Microwave_Quesdilla
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Microwave_Risotto > data/Cookbook:Microwave_Risotto
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Microwaved_Artichoke > data/Cookbook:Microwaved_Artichoke
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Midwestern_Chicken_Wings > data/Cookbook:Midwestern_Chicken_Wings
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Milk_toast > data/Cookbook:Milk_toast
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Milkshake > data/Cookbook:Milkshake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mille_Crêpe > data/Cookbook:Mille_Crêpe
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mincemeat_Tart > data/Cookbook:Mincemeat_Tart
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Minestrone_alla_Capucina > data/Cookbook:Minestrone_alla_Capucina
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Minestrone_of_Rice_and_Turnips > data/Cookbook:Minestrone_of_Rice_and_Turnips
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Miso_Soup > data/Cookbook:Miso_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mjeddrah > data/Cookbook:Mjeddrah
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mocha_icing > data/Cookbook:Mocha_icing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Modak > data/Cookbook:Modak
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Molasses_Cookies > data/Cookbook:Molasses_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Molasses_Taffy > data/Cookbook:Molasses_Taffy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Moqueca_de_Peixe > data/Cookbook:Moqueca_de_Peixe
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Moules_Mariniere > data/Cookbook:Moules_Mariniere
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mudde > data/Cookbook:Mudde
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mung_Beans_and_Brown_Rice > data/Cookbook:Mung_Beans_and_Brown_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Mussels_with_Potatoes > data/Cookbook:Mussels_with_Potatoes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Müsli > data/Cookbook:Müsli
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Nachos > data/Cookbook:Nachos
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Neapolitan_sauce > data/Cookbook:Neapolitan_sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Neapolitan_soup > data/Cookbook:Neapolitan_soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:New_Mexico_Pork_Tamales > data/Cookbook:New_Mexico_Pork_Tamales
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Nick\'s_Cinnamon_Chicken > data/Cookbook:Nick\'s_Cinnamon_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:No-Bake_Chocolate_Chip_Cookie_Pie > data/Cookbook:No-Bake_Chocolate_Chip_Cookie_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:No-Bake_Cookies > data/Cookbook:No-Bake_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Not_Quite_Eggs_Benedict > data/Cookbook:Not_Quite_Eggs_Benedict
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Nut_Roll > data/Cookbook:Nut_Roll
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Oatcake > data/Cookbook:Oatcake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Oatmeal_Banana_Waffle > data/Cookbook:Oatmeal_Banana_Waffle
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Oatmeal_Raisin_Cookies > data/Cookbook:Oatmeal_Raisin_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Olive_Oil_Bread > data/Cookbook:Olive_Oil_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Omelet_Recipes > data/Cookbook:Omelet_Recipes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:One-Hour_Thanksgiving_Dinner > data/Cookbook:One-Hour_Thanksgiving_Dinner
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Onion_Chutney > data/Cookbook:Onion_Chutney
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Onion_Dip > data/Cookbook:Onion_Dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Onion_Soup > data/Cookbook:Onion_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Orange_Hot_Chocolate > data/Cookbook:Orange_Hot_Chocolate
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Orange_Julius > data/Cookbook:Orange_Julius
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Orange_Sherbet_Smoothie > data/Cookbook:Orange_Sherbet_Smoothie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Original_Pineapple_Upside-Down_Cake > data/Cookbook:Original_Pineapple_Upside-Down_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ossobuco_Alla_Milanese > data/Cookbook:Ossobuco_Alla_Milanese
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pad_Thai > data/Cookbook:Pad_Thai
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pancake > data/Cookbook:Pancake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pancakes_\(Vegan\) > data/Cookbook:Pancakes_\(Vegan\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Panch_Puran > data/Cookbook:Panch_Puran
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Papas_a_la_Huancaína > data/Cookbook:Papas_a_la_Huancaína
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Paprika_Chicken > data/Cookbook:Paprika_Chicken
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pasta_Marinata > data/Cookbook:Pasta_Marinata
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pasta_Romanov > data/Cookbook:Pasta_Romanov
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pate_Chinois > data/Cookbook:Pate_Chinois
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pavlova > data/Cookbook:Pavlova
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Peach_Cobbler > data/Cookbook:Peach_Cobbler
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Peanut_Brittle > data/Cookbook:Peanut_Brittle
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Peanut_Sauce > data/Cookbook:Peanut_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pear_Pie > data/Cookbook:Pear_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pesto > data/Cookbook:Pesto
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pezzetti_di_Cavallo > data/Cookbook:Pezzetti_di_Cavallo
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pickert > data/Cookbook:Pickert
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pico_de_Gallo > data/Cookbook:Pico_de_Gallo
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pierogi > data/Cookbook:Pierogi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pineapple_Tarts > data/Cookbook:Pineapple_Tarts
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pineapple_Teriyaki > data/Cookbook:Pineapple_Teriyaki
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pineapple_Upside-Down_Cake_in_a_Skillet > data/Cookbook:Pineapple_Upside-Down_Cake_in_a_Skillet
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pineapple_upside-down_cake > data/Cookbook:Pineapple_upside-down_cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pizza > data/Cookbook:Pizza
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pizza_Sauce > data/Cookbook:Pizza_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pizza_Vanegas > data/Cookbook:Pizza_Vanegas
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Piñon_\(Spanish_Stovetop_Pot_Pie\) > data/Cookbook:Piñon_\(Spanish_Stovetop_Pot_Pie\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Plank-Grilled_Salmon > data/Cookbook:Plank-Grilled_Salmon
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Po\'_Boy > data/Cookbook:Po\'_Boy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Polenta > data/Cookbook:Polenta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pork_Pot_Pie > data/Cookbook:Pork_Pot_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potage_Parmentier > data/Cookbook:Potage_Parmentier
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato-Chickpea_Curry > data/Cookbook:Potato-Chickpea_Curry
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato_Casserole_\(Rakott_Krumpli\) > data/Cookbook:Potato_Casserole_\(Rakott_Krumpli\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato_Chip > data/Cookbook:Potato_Chip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato_Samosas_\(Aloo_Pies\) > data/Cookbook:Potato_Samosas_\(Aloo_Pies\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato_Skins > data/Cookbook:Potato_Skins
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potato_recipes > data/Cookbook:Potato_recipes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Potatoes_on_the_Half-Shell > data/Cookbook:Potatoes_on_the_Half-Shell
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pound_Cake > data/Cookbook:Pound_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Poutine > data/Cookbook:Poutine
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Prekmurska_gibanica > data/Cookbook:Prekmurska_gibanica
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Preserved_Lemon > data/Cookbook:Preserved_Lemon
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pretzel > data/Cookbook:Pretzel
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Puliyodarai_Quick > data/Cookbook:Puliyodarai_Quick
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pulse_Chutney > data/Cookbook:Pulse_Chutney
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pumpkin_Pie > data/Cookbook:Pumpkin_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pumpkin_Scones > data/Cookbook:Pumpkin_Scones
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Pupusa > data/Cookbook:Pupusa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Purée_Mongole > data/Cookbook:Purée_Mongole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Quesadilla > data/Cookbook:Quesadilla
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Queso > data/Cookbook:Queso
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Quiche > data/Cookbook:Quiche
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Quick_Marshmallow_Rice_Squares > data/Cookbook:Quick_Marshmallow_Rice_Squares
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Quick_and_Delicious_Pineapple_Upside-Down_Cake > data/Cookbook:Quick_and_Delicious_Pineapple_Upside-Down_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rainbow_Jell-O > data/Cookbook:Rainbow_Jell-O
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Raisin_Oatmeal_Muffins > data/Cookbook:Raisin_Oatmeal_Muffins
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Raita > data/Cookbook:Raita
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ranch_Dressing > data/Cookbook:Ranch_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ratatouille > data/Cookbook:Ratatouille
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Red_Bean_Paste_\(Anko\) > data/Cookbook:Red_Bean_Paste_\(Anko\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Red_Chile_Sauce > data/Cookbook:Red_Chile_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Red_Cross_Fudge > data/Cookbook:Red_Cross_Fudge
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Red_Devils > data/Cookbook:Red_Devils
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Refried_Beans > data/Cookbook:Refried_Beans
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Requested_Recipes > data/Cookbook:Requested_Recipes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Reuben_Sandwich > data/Cookbook:Reuben_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rhubarb_Cake > data/Cookbook:Rhubarb_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rhubarb_Crumble > data/Cookbook:Rhubarb_Crumble
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rhubarb_Fool > data/Cookbook:Rhubarb_Fool
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_-_Molded_\(Arroz_Tapado\) > data/Cookbook:Rice_-_Molded_\(Arroz_Tapado\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_Bubble_cake > data/Cookbook:Rice_Bubble_cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_Pilaf > data/Cookbook:Rice_Pilaf
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_Pudding > data/Cookbook:Rice_Pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_an\'_Peas > data/Cookbook:Rice_an\'_Peas
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_and_Beef_Soup > data/Cookbook:Rice_and_Beef_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rice_in_Fish_Broth-Sayyadieh > data/Cookbook:Rice_in_Fish_Broth-Sayyadieh
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ricotta_Lasagne > data/Cookbook:Ricotta_Lasagne
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rigatoni_pasta_with_Ricotta_in_Tomato_Cream_Sauce > data/Cookbook:Rigatoni_pasta_with_Ricotta_in_Tomato_Cream_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Risotto > data/Cookbook:Risotto
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rissoles > data/Cookbook:Rissoles
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roast_Chicken_on_Salt > data/Cookbook:Roast_Chicken_on_Salt
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roasted_Brined_Turkey > data/Cookbook:Roasted_Brined_Turkey
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roasted_Oysters_with_Madeira > data/Cookbook:Roasted_Oysters_with_Madeira
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roasted_Vegetable_Pasta > data/Cookbook:Roasted_Vegetable_Pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rolls > data/Cookbook:Rolls
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rosemary_Bread > data/Cookbook:Rosemary_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rosemary_Garlic_Baked_Potatoes > data/Cookbook:Rosemary_Garlic_Baked_Potatoes
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Rosół > data/Cookbook:Rosół
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roti > data/Cookbook:Roti
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Roux > data/Cookbook:Roux
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:S\'more > data/Cookbook:S\'more
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Saffron_Rice > data/Cookbook:Saffron_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Salsa > data/Cookbook:Salsa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Salt_Cod_and_Potato_Casserole_\(Bacalhau_à_Gomes_de_Sá\) > data/Cookbook:Salt_Cod_and_Potato_Casserole_\(Bacalhau_à_Gomes_de_Sá\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Samosa > data/Cookbook:Samosa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:San_Francisco_style_Scallop_Ceviche > data/Cookbook:San_Francisco_style_Scallop_Ceviche
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Saucepan_Fudge_Crackle_Cookies > data/Cookbook:Saucepan_Fudge_Crackle_Cookies
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Scrambled_Eggs > data/Cookbook:Scrambled_Eggs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Seafood_Kebabs_with_Zhoug_Sauce > data/Cookbook:Seafood_Kebabs_with_Zhoug_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sesame_Shrimp_Toast > data/Cookbook:Sesame_Shrimp_Toast
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Shakshuka > data/Cookbook:Shakshuka
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sheer_khurma > data/Cookbook:Sheer_khurma
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Shepherd\'s_Pie > data/Cookbook:Shepherd\'s_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Shrimp_Fritters_\(Accra\) > data/Cookbook:Shrimp_Fritters_\(Accra\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Shrimp_and_Cassava_Sauce_of_Brazil_\(Bobó_de_Camarao\) > data/Cookbook:Shrimp_and_Cassava_Sauce_of_Brazil_\(Bobó_de_Camarao\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Silvash_Gombotz > data/Cookbook:Silvash_Gombotz
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Simple_Nachos > data/Cookbook:Simple_Nachos
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Simple_Roasted_Oysters > data/Cookbook:Simple_Roasted_Oysters
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sirniki > data/Cookbook:Sirniki
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Six_Layer_Casserole > data/Cookbook:Six_Layer_Casserole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sockerdricka > data/Cookbook:Sockerdricka
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Soda_Bread > data/Cookbook:Soda_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Soup_with_Supplì > data/Cookbook:Soup_with_Supplì
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sour_Cream_Dip > data/Cookbook:Sour_Cream_Dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Southwest_Pasta > data/Cookbook:Southwest_Pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Southwestern_Scramble > data/Cookbook:Southwestern_Scramble
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Soy_Protein_Bread > data/Cookbook:Soy_Protein_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Space_Cake > data/Cookbook:Space_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spaghetti_alla_Carbonara > data/Cookbook:Spaghetti_alla_Carbonara
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spanish_Flan > data/Cookbook:Spanish_Flan
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spanish_Omelet > data/Cookbook:Spanish_Omelet
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spiced_Pumpkin_Soup > data/Cookbook:Spiced_Pumpkin_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spicy_Chicken_Casserole > data/Cookbook:Spicy_Chicken_Casserole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Spicy_feta_burger > data/Cookbook:Spicy_feta_burger
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sponge_Cake > data/Cookbook:Sponge_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sprout_Salad > data/Cookbook:Sprout_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Stargazy_Pie > data/Cookbook:Stargazy_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Steak_tartare > data/Cookbook:Steak_tartare
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Steamed_Artichoke > data/Cookbook:Steamed_Artichoke
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Steamed_Buns_with_BBQ_Pork > data/Cookbook:Steamed_Buns_with_BBQ_Pork
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Steamed_Rice > data/Cookbook:Steamed_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Stewed_Oysters > data/Cookbook:Stewed_Oysters
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Stewed_dry_figs_dessert > data/Cookbook:Stewed_dry_figs_dessert
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Strudel > data/Cookbook:Strudel
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Stuffed_Mushrooms_with_Crabmeat > data/Cookbook:Stuffed_Mushrooms_with_Crabmeat
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Stuffed_Portabella_Mushrooms > data/Cookbook:Stuffed_Portabella_Mushrooms
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Succotash > data/Cookbook:Succotash
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sunglow_Motel-Cafe_Pickle_Pie > data/Cookbook:Sunglow_Motel-Cafe_Pickle_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sunshine_Cake > data/Cookbook:Sunshine_Cake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sushi > data/Cookbook:Sushi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Swedish_Meatballs > data/Cookbook:Swedish_Meatballs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sweet_Cornbread > data/Cookbook:Sweet_Cornbread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sweet_and_Sour > data/Cookbook:Sweet_and_Sour
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Sweet_pongal > data/Cookbook:Sweet_pongal
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Swiss_pudding > data/Cookbook:Swiss_pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tabouli > data/Cookbook:Tabouli
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tabula > data/Cookbook:Tabula
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tadka_dhal > data/Cookbook:Tadka_dhal
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tahini_Goddess_Dressing > data/Cookbook:Tahini_Goddess_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tandoori_masala > data/Cookbook:Tandoori_masala
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tangerine_Jelly > data/Cookbook:Tangerine_Jelly
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tarbes_Salad > data/Cookbook:Tarbes_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tartiflette > data/Cookbook:Tartiflette
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tater_Tot_Casserole > data/Cookbook:Tater_Tot_Casserole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tea_Eggs > data/Cookbook:Tea_Eggs
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tempura > data/Cookbook:Tempura
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Teriyaki > data/Cookbook:Teriyaki
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Texas_Easy_Chili > data/Cookbook:Texas_Easy_Chili
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Thousand_Island_Dressing > data/Cookbook:Thousand_Island_Dressing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Three_Ginger_Soup > data/Cookbook:Three_Ginger_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tiramisu > data/Cookbook:Tiramisu
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Toasted_Cheese_Sandwich > data/Cookbook:Toasted_Cheese_Sandwich
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Toasted_Ravioli > data/Cookbook:Toasted_Ravioli
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tofu > data/Cookbook:Tofu
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tofu_Pancake > data/Cookbook:Tofu_Pancake
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_Coulis > data/Cookbook:Tomato_Coulis
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_Curry > data/Cookbook:Tomato_Curry
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_Pasta > data/Cookbook:Tomato_Pasta
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_Salad > data/Cookbook:Tomato_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_Sauce_Piquante > data/Cookbook:Tomato_Sauce_Piquante
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomato_and_Onion_Salad > data/Cookbook:Tomato_and_Onion_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tomatoes_with_Cheese_Stuffing > data/Cookbook:Tomatoes_with_Cheese_Stuffing
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Traditional_Pilau_Rice > data/Cookbook:Traditional_Pilau_Rice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tri-colored_Autumn_Rice_Balls > data/Cookbook:Tri-colored_Autumn_Rice_Balls
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tuna_Curry > data/Cookbook:Tuna_Curry
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Tuna_Salad > data/Cookbook:Tuna_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Turkey_Biscuit > data/Cookbook:Turkey_Biscuit
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Turkey_Soup > data/Cookbook:Turkey_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Turkey_Wrap > data/Cookbook:Turkey_Wrap
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Turkey_and_Bacon_Salad > data/Cookbook:Turkey_and_Bacon_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ukrainian_Cabbage_Soup_\(Kapusniak\) > data/Cookbook:Ukrainian_Cabbage_Soup_\(Kapusniak\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ukrainian_Cornmeal_Stuffing_\(Nachynka\) > data/Cookbook:Ukrainian_Cornmeal_Stuffing_\(Nachynka\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Ume-shu > data/Cookbook:Ume-shu
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Umeboshi > data/Cookbook:Umeboshi
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Upeseru > data/Cookbook:Upeseru
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Valencian_paella > data/Cookbook:Valencian_paella
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Veal_with_lima_beans > data/Cookbook:Veal_with_lima_beans
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Vegetable_Pie > data/Cookbook:Vegetable_Pie
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Vegetable_Stew_and_Dumplings > data/Cookbook:Vegetable_Stew_and_Dumplings
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Vegetarian_Gravy > data/Cookbook:Vegetarian_Gravy
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Vegetarian_Soft_Tacos > data/Cookbook:Vegetarian_Soft_Tacos
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Waldorf_Salad > data/Cookbook:Waldorf_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Wheat_grass_juice > data/Cookbook:Wheat_grass_juice
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Whipped_Cream > data/Cookbook:Whipped_Cream
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:White_Bread > data/Cookbook:White_Bread
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:White_Sauce > data/Cookbook:White_Sauce
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Wiejska > data/Cookbook:Wiejska
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Wild_Spinach_and_Lemon_Salad > data/Cookbook:Wild_Spinach_and_Lemon_Salad
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Windsor_pudding > data/Cookbook:Windsor_pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Wonton_Soup > data/Cookbook:Wonton_Soup
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Wonton_Wrapper > data/Cookbook:Wonton_Wrapper
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Yam_casserole > data/Cookbook:Yam_casserole
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Yogurt_Dip > data/Cookbook:Yogurt_Dip
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Yorkshire_Pudding > data/Cookbook:Yorkshire_Pudding
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Yorkshire_Pudding_\(Vegan\) > data/Cookbook:Yorkshire_Pudding_\(Vegan\)
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Yurvarlak > data/Cookbook:Yurvarlak
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Zupa_Ogórkowa > data/Cookbook:Zupa_Ogórkowa
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Zuppa_Toscana > data/Cookbook:Zuppa_Toscana
xsltproc -html stripWikiRecipe.xsl temp/Cookbook:Øllebrød > data/Cookbook:Øllebrød
